version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:local
    ports:
      - 8080:8080
      - 18080:18080
    command: "volume -mserver=master:9333 -port=8080 -ip=volume -preStopSeconds=1"
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:local
    ports:
      - 8888:8888
      - 18888:18888
    command: '-v=9 filer -master="master:9333"'
    restart: on-failure
    volumes:
      - ./notification.toml:/etc/seaweedfs/notification.toml
    depends_on:
      - master
      - volume
      - rabbitmq
      - replicate
    environment:
      RABBIT_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"
  replicate:
    image: chrislusf/seaweedfs:local
    command: '-v=9 filer.replicate'
    restart: on-failure
    volumes:
      - ./notification.toml:/etc/seaweedfs/notification.toml
      - ./replication.toml:/etc/seaweedfs/replication.toml
    depends_on:
      - rabbitmq
    environment:
      RABBIT_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"
  s3:
    image: chrislusf/seaweedfs:local
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
  rabbitmq:
    image: rabbitmq:3.8.10-management-alpine
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{queue,debug}]"