name: "go: build binary"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/go
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2

    - name: Get dependencies
      run: |
        cd weed; go get -v -t -d ./...

    - name: Build
      run: cd weed; go build -tags "elastic gocdk sqlite ydb tikv" -v .

    - name: Test
      run: cd weed; go test -tags "elastic gocdk sqlite ydb tikv" -v ./...
