name: "go: build binary"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/go
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v2

    - name: Get dependencies
      run: |
        cd weed; go get -v -t -d ./...

    - name: Build
      run: cd weed; go build -tags "elastic gocdk sqlite ydb tikv" -v .

    - name: Test
      run: cd weed; go test -tags "elastic gocdk sqlite ydb tikv" -v ./...
