name: "go: build binary"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/go
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v2

    - name: Get dependencies
      run: |
        cd weed; go get -v -t -d ./...

    - name: Build
      run: cd weed; go build -tags "elastic gocdk sqlite ydb tikv rclone" -v .

    - name: Test
      run: cd weed; go test -tags "elastic gocdk sqlite ydb tikv rclone" -v ./...
