name: "go: build binary"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/go
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

    - name: Get dependencies
      run: |
        cd weed; go get -v -t -d ./...

    - name: Build
      run: cd weed; go build -tags "elastic gocdk sqlite ydb tikv" -v .

    - name: Test
      run: cd weed; go test -tags "elastic gocdk sqlite ydb tikv" -v ./...
