name: "go: build binary"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}/go
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v2

    - name: Get dependencies
      run: |
        cd weed; go get -v -t -d ./...

    - name: Build
      run: cd weed; go build -tags "elastic gocdk sqlite ydb tikv" -v .

    - name: Test
      run: cd weed; go test -tags "elastic gocdk sqlite ydb tikv" -v ./...
